BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_global_task_aug.yaml

USE_CPU: False
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1

TENSORBOARD_DIR: data/out/paper/tensorboard_dirs/cma_aug
CHECKPOINT_FOLDER: data/out/paper/checkpoints/cma_aug
EVAL_CKPT_PATH_DIR: data/out/paper/checkpoints/cma_aug
VIDEO_DIR: data/out/paper/videos/cma_aug
VIDEO_OPTION: ["disk"]

TRAINER_NAME: "speaker_dagger" 
ENV_NAME:  "VLNCEDaggerEnv"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 157232
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma/global_speaker_aug_trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
