BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_global_task.yaml

USE_CPU: False
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1

TENSORBOARD_DIR: data/out/paper/tensorboard_dirs/cma_pm_aug_tune
CHECKPOINT_FOLDER: data/out/paper/checkpoints/cma_pm_aug_tune
EVAL_CKPT_PATH_DIR: data/out/paper/checkpoints/cma_pm_aug_tune

TRAINER_NAME: "speaker_dagger" 
ENV_NAME:  "VLNCEDaggerEnv"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 10819
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma/global_speaker_pm_aug_tune_trajectories.lmdb
  LOAD_FROM_CKPT: True
  CKPT_TO_LOAD: data/out/paper/checkpoints/cma_pm_aug/best_checkpoint.pth # REPLACE

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
