BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_global_task_aug.yaml

USE_CPU: False
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1

TENSORBOARD_DIR: data/out/paper/tensorboard_dirs/seq2seq_aug
CHECKPOINT_FOLDER: data/out/paper/checkpoints/seq2seq_aug
EVAL_CKPT_PATH_DIR: data/out/paper/checkpoints/seq2seq_aug

TRAINER_NAME: "speaker_dagger" 
ENV_NAME:  "VLNCEDaggerEnv"

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 15
  UPDATE_SIZE: 157232
  BATCH_SIZE: 1
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/seq2seq/global_speaker_aug_trajectories.lmdb
