# ------------------------------------------------------------------------------
# CONFIGURATION FILE FOR THE 
#     Dynamic Waypoint VLN-CE Planner Task
# ------------------------------------------------------------------------------
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TYPE: "DwpSimVLNCE"
  AGENT_0:
    SENSORS: [
      RGB_SENSOR, 
      DEPTH_SENSOR
    ]
  GRID_SIZE: 1.0
  FORWARD_STEP_SIZE: 1.0
  TURN_ANGLE: 90
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    # WIDTH: 128  # used for VisualCNN
    # HEIGHT: 128
    WIDTH: 224    # used for pretrained ResNet50
    HEIGHT: 224
  DEPTH_SENSOR:
    # WIDTH: 128  # used for VisualCNN
    # HEIGHT: 128
    WIDTH: 256    # used for pretrained DDPPO ResNet50
    HEIGHT: 256
  METADATA_DIR: data/datasets/metadata
  SCENE_DATASET: mp3d
TASK:
  TYPE: VLN-v0
  SENSORS: [
    EGOMAP_SENSOR,
    ACTION_MAP,
    GEOMETRIC_MAP,
    COLLISION,
    POINTGOAL_WITH_GPS_COMPASS_SENSOR
    INSTRUCTION_SENSOR,
    VLN_ORACLE_ACTION_SENSOR,
    VLN_ORACLE_PROGRESS_SENSOR
  ]
  GOAL_SENSOR_UUID: pointgoal
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2
  POSSIBLE_ACTIONS: [
    STOP, 
    MOVE_FORWARD, 
    TURN_LEFT, 
    TURN_RIGHT
    ]
  INSTRUCTION_SENSOR_UUID: instruction
  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL,
    PATH_LENGTH,
    ORACLE_SUCCESS,
    STEPS_TAKEN
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  SPL:
    SUCCESS_DISTANCE: 3.0
  ORACLE_SUCCESS:
    SUCCESS_DISTANCE: 3.0
  GEOMETRIC_MAP:
    MAP_SIZE: 400
    INTERNAL_MAP_SIZE: 1200
    MAP_RESOLUTION: 0.1
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 10000
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT
  ACTION_MAP:
    MAP_SIZE: 9
    MAP_RESOLUTION: 1.0
  EGOMAP_SENSOR:
    MAP_SIZE: 15
    MAP_RESOLUTION: 0.2
DATASET:
  TYPE: VLN-CE-v1
  SPLIT: train
  DATA_PATH: data/datasets/vlnce/R2R_VLNCE_v1-2_preprocessed/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets/