BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_global_task.yaml

USE_CPU: False
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1

TENSORBOARD_DIR: data/out/dagger/tensorboard_dirs/cma_global
CHECKPOINT_FOLDER: data/out/dagger/checkpoints/cma_global
EVAL_CKPT_PATH_DIR: data/out/dagger/checkpoints/cma_global
VIDEO_DIR: data/out/dagger/videos/cma_global
VIDEO_OPTION: # ["disk"]
LOG_FILE: "dagger_cma_global.log"

TRAINER_NAME: "dagger" 
ENV_NAME:  "VLNCEDaggerEnv" 

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 100

DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  # reduce parameter update_size for testing purposes
  UPDATE_SIZE: 100 
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma/global_trajectories

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
