BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_local_task.yaml

USE_CPU: True
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 4

TENSORBOARD_DIR: data/out/dagger/tensorboard_dirs/cma_local
CHECKPOINT_FOLDER: data/out/dagger/checkpoints/cma_local
EVAL_CKPT_PATH_DIR: data/out/dagger/checkpoints/cma_local
VIDEO_DIR: data/out/dagger/videos/cma_local
VIDEO_OPTION: ["disk"]
LOG_FILE: "dagger_cma_local.log"

TRAINER_NAME: "dagger" 
ENV_NAME:  "VLNCEDaggerEnv" 

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 100

DAGGER:
  ITERATIONS: 1
  EPOCHS: 45
  # reduce parameter update_size for testing purposes
  UPDATE_SIZE: 10819 
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma/local_trajectories

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True
